### ISSUE TITLE
frac not expanding correctly

### ISSUE THREAD

**Issue by ghost** [gillescastel/latex-snippets#3]
Hi, great snippets collection and tutorials. My setup seems to be faulty since some snippets don't work correctly. A good example are the frac-snippets of your tutorial, which behave in the following way on my computer:
(Pointer position indicated by a star)
/ -> \frac{}{*}
3/ -> 3\frac{}{}*

Here is my config file:
![image](https://user-images.githubusercontent.com/26022993/67321607-02658400-f510-11e9-8699-8f9a9ec12c9c.png)
Do you have any ideas what i can do?

**Comment by siemdejong** [comment]
I know this issue is quite old and may be resolved for you already, but in order to make fractions work like you would expect, the snippet should be invoked within a 'math' context as defined by the math function in the tex.snippets file.

https://github.com/gillescastel/latex-snippets/blob/ce1746d4a7b46e9e6da1a8d473ab24f734b2fa26/tex.snippets#L136-L139

Thanks to the snippets, you can establish such an environment for example by typing `dm`. The short version of the displaymath environment `\[...\]` will then take it's place, allowing you to use snippets that require the math context.

**Comment by sashkopavlenko** [comment]
Had the same issue, because copied fraction snippets from [blog post ](https://castel.dev/post/lecture-notes-1/#fractions) where snippet that uses `{VISUAL}` has auto expand option. 

For anyone who faces the same, make sure this snippet doesn't have `A` in the definition:
https://github.com/gillescastel/latex-snippets/blob/ce1746d4a7b46e9e6da1a8d473ab24f734b2fa26/tex.snippets#L141-L143
