### ISSUE TITLE
TexMathZone Questions

### ISSUE THREAD

**Issue by yushangakki** [gillescastel/latex-snippets#5]
HI, how to add `\begin{align}` as one of the math context in the `define math()` functions? THank you!

**Comment by liuzh1206** [comment]
I also encountered this problem, and I find this website https://tex.stackexchange.com/questions/416030/how-do-i-make-vim-highlight-math-properly-in-the-align-environment.
I did it according to this website, but it didn't work. I find out it's because vim con't identify align environment, so I add the follow code to`~/.vim/bundle/vimtex/after/ftplugin/tex.vim` last line.
```vim
call TexNewMathZone("E","align",1)
```
then it works.
If you like, you can also add the following code.
```vim
call TexNewMathZone("F","alignat",1)
call TexNewMathZone("G","equation",1)
call TexNewMathZone("H","flalign",1)
call TexNewMathZone("I","gather",1)
call TexNewMathZone("J","multline",1)
call TexNewMathZone("K","xalignat",1)
```

**Comment by yushangakki** [comment]
Thank you, it helps
